amazonProperties:
  endpointUrl: https://s3.ap-southeast-1.amazonaws.com
  accessKey: AKIA4IQR3FNC2Q4P656T
  secretKey: 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
  bucketName: thesisbucket
  region: ap-southeast-1

firebase:
  googleCredentials: config/firebase-service-account.json